import React, { useState } from 'react';
import { ArrowLeft, CalendarDays, Check, ChevronRight, Gift, ShieldCheck, Sparkles, Target, Trophy, Zap } from 'lucide-react';

interface SavingsGoalsProps { onBack: () => void; transactions: unknown[]; }
interface SavingGoal { id: string; title: string; target: number; current: number; deadline: string; category: string; reward: string; streak: number; level: number; icon: string; }
interface Challenge { id: string; title: string; description: string; points: number; duration: string; completed: boolean; icon: string; }

const initialGoals: SavingGoal[] = [
  { id: '1', title: 'Emergency Fund', target: 50000, current: 12000, deadline: '2026-12-31', category: 'Security', reward: 'Financial Freedom Badge', streak: 15, level: 3, icon: '🛡️' },
  { id: '2', title: 'New Laptop', target: 65000, current: 45000, deadline: '2026-06-15', category: 'Gadgets', reward: 'Tech Master Achievement', streak: 8, level: 2, icon: '⌁' },
  { id: '3', title: 'Vacation Plan', target: 30000, current: 15000, deadline: '2026-10-30', category: 'Travel', reward: 'Explorer Badge', streak: 12, level: 4, icon: '✈' },
];
const initialChallenges: Challenge[] = [
  { id: '1', title: 'No Swiggy Week', description: 'Avoid food delivery for 7 days', points: 100, duration: '5 days left', completed: false, icon: '◌' },
  { id: '2', title: 'Daily Saver', description: 'Save at least ₹100 every day', points: 50, duration: '3 days left', completed: false, icon: '₹' },
  { id: '3', title: 'Budget Master', description: 'Stay within budget for all categories', points: 200, duration: '15 days left', completed: true, icon: '◎' },
];
const money = (value: number) => `₹${value.toLocaleString('en-IN')}`;

const SavingsGoals: React.FC<SavingsGoalsProps> = ({ onBack }) => {
  const [userLevel] = useState(5);
  const [totalPoints, setTotalPoints] = useState(1250);
  const [currentStreak] = useState(7);
  const [savingGoals, setSavingGoals] = useState(initialGoals);
  const [challenges] = useState(initialChallenges);

  const addToGoal = (id: string, amount: number) => { setSavingGoals((goals) => goals.map((goal) => goal.id === id ? { ...goal, current: Math.min(goal.current + amount, goal.target) } : goal)); setTotalPoints((points) => points + Math.floor(amount / 10)); };
  const totalSaved = savingGoals.reduce((sum, goal) => sum + goal.current, 0);
  const totalTarget = savingGoals.reduce((sum, goal) => sum + goal.target, 0);

  return <div className="mx-auto max-w-7xl space-y-7 px-4 py-6 sm:px-6 lg:px-10 lg:py-9">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><button onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-slate-500 transition hover:text-[#5867bb]"><ArrowLeft className="h-4 w-4" /> Back to overview</button><p className="eyebrow">Wealth building</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.05em] text-slate-950 sm:text-5xl">Save with momentum.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">Give every goal a name, a pace, and a little bit of positive pressure. Progress feels better when you can see it.</p></div><div className="flex items-center gap-2 rounded-2xl border border-teal-100 bg-teal-50 px-4 py-3 text-sm font-bold text-teal-800"><Sparkles className="h-4 w-4" /> {totalPoints} points earned</div></div>
    <section className="grid gap-4 md:grid-cols-4"><Stat label="Current level" value={`Level ${userLevel}`} icon={Trophy} tone="dark" /><Stat label="Total points" value={totalPoints.toLocaleString()} icon={Sparkles} tone="mint" /><Stat label="Day streak" value={`${currentStreak} days`} icon={Zap} tone="sand" /><Stat label="Saved so far" value={money(totalSaved)} icon={ShieldCheck} tone="violet" /></section>
    <section className="premium-card p-5 sm:p-7"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="eyebrow">Portfolio progress</p><h2 className="mt-2 text-xl font-semibold text-slate-950">You are building a stronger buffer.</h2><p className="mt-1 text-sm text-slate-500">{money(totalSaved)} saved across {savingGoals.length} active goals.</p></div><div className="w-full max-w-md"><div className="mb-2 flex justify-between text-xs font-bold text-slate-500"><span>Overall progress</span><span>{Math.round((totalSaved / totalTarget) * 100)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600 transition-all" style={{ width: `${Math.min((totalSaved / totalTarget) * 100, 100)}%` }} /></div></div></div></section>
    <section className="space-y-4"><div><p className="eyebrow">Active goals</p><h2 className="mt-2 text-xl font-semibold tracking-tight text-slate-950">A clear path to your next milestones.</h2></div><div className="grid gap-4 lg:grid-cols-3">{savingGoals.map((goal) => { const progress = Math.min((goal.current / goal.target) * 100, 100); return <article key={goal.id} className="premium-card p-5 transition hover:-translate-y-0.5 hover:shadow-[0_18px_45px_rgba(15,23,42,0.08)]"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-teal-50 text-xl text-teal-700">{goal.icon}</div><div><h3 className="font-bold text-slate-900">{goal.title}</h3><p className="mt-0.5 text-xs text-slate-400">{goal.category} · Level {goal.level}</p></div></div><Target className="h-4 w-4 text-slate-300" /></div><div className="mt-7 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">Progress</p><p className="mt-1 text-lg font-bold text-slate-900">{money(goal.current)} <span className="text-xs font-medium text-slate-400">/ {money(goal.target)}</span></p></div><span className="text-sm font-bold text-teal-700">{progress.toFixed(0)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600 transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-4 flex items-center justify-between text-xs text-slate-400"><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5" /> {goal.deadline}</span><span className="inline-flex items-center gap-1"><Zap className="h-3.5 w-3.5" /> {goal.streak} day streak</span></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500"><Gift className="h-3.5 w-3.5 text-orange-500" /> {goal.reward}</div><div className="mt-4 flex gap-2"><button onClick={() => addToGoal(goal.id, 100)} className="flex-1 rounded-xl bg-[#222d4b] px-3 py-2.5 text-xs font-bold text-white transition hover:bg-[#3e4c91] active:scale-[0.98]">Add ₹100</button><button onClick={() => addToGoal(goal.id, 500)} className="flex-1 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold text-slate-700 transition hover:border-[#aeb8ed] hover:text-[#5867bb] active:scale-[0.98]">Add ₹500</button></div></article>; })}</div></section>
    <section className="premium-card p-5 sm:p-7"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Weekly challenges</p><h2 className="mt-2 text-xl font-semibold tracking-tight text-slate-950">Small challenges, real behavior change.</h2></div><Zap className="h-5 w-5 text-orange-500" /></div><div className="grid gap-3 md:grid-cols-3">{challenges.map((challenge) => <div key={challenge.id} className="flex items-center gap-3 rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-lg font-bold text-teal-700 shadow-sm">{challenge.completed ? <Check className="h-5 w-5" /> : challenge.icon}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-bold text-slate-800">{challenge.title}</p><span className="shrink-0 text-xs font-bold text-teal-700">{challenge.points} pts</span></div><p className="mt-1 text-xs text-slate-400">{challenge.description}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">{challenge.duration}</p></div><ChevronRight className="h-4 w-4 text-slate-300" /></div>)}</div></section>
  </div>;
};

const Stat = ({ label, value, icon: Icon, tone }: { label: string; value: string; icon: React.ElementType; tone: string }) => <div className={`metric-card ${tone === 'dark' ? 'metric-card-dark' : tone === 'mint' ? 'metric-card-mint' : tone === 'sand' ? 'metric-card-sand' : 'bg-violet-100 text-violet-950'}`}><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] opacity-60">{label}</p><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p></div><Icon className="h-5 w-5 opacity-70" /></div></div>;

export default SavingsGoals;
