
export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
];

export const translations = {
  en: {
    // Common UI Elements
    language: "Language",
    dashboard: "Dashboard",
    addExpense: "Add Expense",
    insights: "AI Insights",
    coach: "Finance Coach",
    budgetPlanner: "Budget Planner",
    savingsGoals: "Savings Goals",
    billReminder: "Bill Reminder",
    expenseChat: "Expense Chat",
    spendingLimits: "Spending Limits",
    gamification: "Save to Win",
    monthlyReport: "Monthly Report",
    smartSuggestions: "Smart Suggestions",

    // Dashboard
    yourFinancialCompanion: "Your intelligent financial companion with advanced features",
    selectMonth: "Select Month",
    totalBalance: "Total Balance",
    totalIncome: "Total Income",
    totalExpenses: "Total Expenses",
    monthlyIncome: "Monthly Income",
    monthlyExpenses: "Monthly Expenses",
    savingsRate: "Savings Rate",
    recentTransactions: "Recent Transactions",
    quickActions: "Quick Actions",
    financialVisualization: "Financial Visualization",
    thisMonth: "This month",
    incomeMinusExpenses: "Income - Expenses",
    netBalance: "Net Balance",
    netBalanceSubtitle: "Your savings are on track! 🚀",
    totalIncomeSubtitle: "Great progress this month! 📈",
    totalExpensesSubtitle: "Keep an eye on spending! 🧐",
    yourAIFinanceCompanion: "Your AI Finance Companion ✨",

    // New Dashboard Features
    calendarTracker: "Calendar Tracker",
    advancedAnalytics: "Advanced Analytics",
    budgetProgress: "Budget Progress",
    moneyMonster: "Money Monster",
    aiSpendingCoach: "AI Spending Coach",
    aiSpendingCoachSubtitle: "Your personal financial advisor",
    warningTitle: "You're spending too much on {category}",
    warningDesc: "₹{amount} spent this month",
    trendTitle: "Spending trend over last 3 months",
    trendDescIncreasing: "Expenses are on an increasing trend",
    trendDescGood: "Good control maintained",
    suggestionTitle: "Smart suggestion for you",
    suggestionDesc: "Try to limit {category} expenses to ₹{limit} next month",
    proTipTitle: "💡 Pro Tip",
    proTipDesc: "Keep logging your expenses regularly for better AI insights. The more data, the smarter recommendations!",
    geoHeatmap: "Geo Heatmap",
    billScanner: "Bill Scanner",
    voiceEntry: "Voice Entry",
    billReminders: "Bill Reminders",
    aiFinanceCoach: "AI Finance Coach",
    smartBudgetPlanner: "DhanSetu Budget Planner",

    // DhanSetu Budget Planner
    budgetSubtitle: "Proper budget planning is the start of savings!",
    monthlyIncomeLabel: "Monthly Income (₹)",
    enterIncomePlaceholder: "e.g., 50000",
    budgetCoachTip: "💡 **Coach Tip**: Brother, I'll create a budget for you based on the 50-30-20 rule. Your savings will be great!",
    totalBudget: "Total Budget",
    totalSpent: "Total Spent",
    remaining: "Remaining",
    overBudget: "Over Budget!",
    budgetBreakdown: "Budget Breakdown",
    smartRecommendations: "Smart Recommendations",
    budgetAlert: "Alert",
    budgetUsageWarning: "You've used {percentage}% of your {category} budget. Consider reducing expenses.",
    budgetTipsTitle: "Budget Tips",
    budgetTip1: "• Follow the 50-30-20 rule: 50% needs, 30% wants, 20% savings",
    budgetTip2: "• Review and adjust your budget monthly",
    budgetTip3: "• Set up automatic transfers for savings",
    budgetTip4: "• Track expenses daily to stay on budget",

    viewAIInsights: "View AI Insights",
    advancedVisualizer: "Advanced Visualizer",

    // AI Insights
    aiInsightsTitle: "AI Insights",
    aiInsightsSubtitle: "Powered by intelligent financial analysis",
    spendingAlert: "Spending Alert",
    spendingIncrease: "You spent more on {category} {timePeriod}",
    spendingIncreaseHi: "You spent more on {category} {timePeriod}", // Fallback/English
    thisMonthValue: "This month: ₹{amount}",
    lastMonthValue: "Last month: ₹{amount}",
    nextMonthPrediction: "Next Month Prediction",
    predictedTotalExpenses: "Predicted total expenses",
    confidence: "{score}% confidence",
    topSpendingCategories: "Top Spending Categories",
    totalExpensesStat: "{percentage}% of total expenses",
    smartSavingsTip: "Smart Savings Tip 💡",
    savingsTipLow: "Try to save 25% of your income for a secure future!",
    savingsTipHigh: "Amazing! Your savings rate is above average.",
    monthlyGoal: "Monthly Goal 🎯",
    monthlyGoalDesc: "Aim to save ₹{amount} this month.",
    spendingPatterns: "Spending Patterns",
    largestExpensePattern: "Your biggest expense is {category} ({percentage}% of total).",
    savingsRatePattern: "Currently you are saving {percentage}% of your income.",
    expenseControlWarning: "⚠️ Brother, expenses are higher than income! Control it.",
    expenseControlSuccess: "✅ Going great! Income is higher than expenses.",
    financialHealthScore: "Financial Health Score",
    outOf100: "OUT OF 100",
    healthScoreExcellent: "You're doing fantastic! Keep building that wealth. 🚀",
    healthScoreGood: "You're on the right track, but there's room for improvement. 💪",
    healthySavings: "Healthy Savings",
    lowSavings: "Low Savings",
    aiAnalyzed: "AI Analyzed",

    // Categories
    food: "Food",
    travel: "Travel",
    entertainment: "Entertainment",
    rent: "Rent",
    income: "Income",
    grocery: "Grocery",
    salary: "Salary",
    freelance: "Freelance",

    // Months
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",

    // Actions
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    back: "Back",
    calculate: "Calculate",

    // Splash Screen
    welcome: "Welcome to",
    smartBudgetAI: "DhanSetu AI",
    yourPersonalFinanceAssistant: "Aapke paiso ka smart saathi",
    getStarted: "Get Started",

    // Gamification
    points: "Points",
    level: "Level",
    streak: "Day Streak",
    badges: "Your Badges",
    challenges: "Today's Challenges",
    leaderboard: "Weekly Leaderboard",
    yourRank: "Your Rank",

    // AddExpense Component
    addTransaction: "Add Transaction",
    recordIncomeOrExpense: "Record your income or expense",
    transactionDetails: "Transaction Details",
    transactionType: "Transaction Type",
    selectType: "Select type",
    expense: "Expense",
    title: "Title",
    titlePlaceholder: "e.g., McDonald's, Salary, Rent",
    amount: "Amount",
    category: "Category",
    selectCategory: "Select category",
    date: "Date",
    pickDate: "Pick a date",
    saveTransaction: "Save Transaction",
    preview: "Preview",
    missingInformation: "Missing Information",
    fillAllFields: "Please fill in all fields to save the transaction.",
    invalidAmount: "Invalid Amount",
    enterValidAmount: "Please enter a valid positive amount.",
    transactionSaved: "Transaction Saved",
    transactionSavedDesc: "Transaction added successfully.",

    // Categories
    shopping: "Shopping",
    healthcare: "Healthcare",
    education: "Education",
    utilities: "Utilities",
    other: "Other",

    // Common phrases
    languageChanged: "Language Changed!",
    congratulations: "Congratulations!",
    newBadgeEarned: "New Badge Earned!",
    keepSaving: "Keep saving to climb higher!",
  },

  hi: {
    // Common UI Elements
    language: "भाषा",
    dashboard: "डैशबोर्ड",
    addExpense: "खर्च जोड़ें",
    insights: "AI अंतर्दृष्टि",
    coach: "वित्त कोच",
    budgetPlanner: "बजट प्लानर",
    savingsGoals: "बचत लक्ष्य",
    billReminder: "बिल रिमाइंडर",
    expenseChat: "खर्च चैट",
    spendingLimits: "खर्च सीमा",
    gamification: "जीतने के लिए बचत",
    monthlyReport: "मासिक रिपोर्ट",
    smartSuggestions: "स्मार्ट सुझाव",

    // Dashboard
    yourFinancialCompanion: "उन्नत सुविधाओं के साथ आपका बुद्धिमान वित्तीय साथी",
    selectMonth: "महीना चुनें",
    totalBalance: "कुल बैलेंस",
    totalIncome: "कुल आय",
    totalExpenses: "कुल खर्च",
    monthlyIncome: "मासिक आय",
    monthlyExpenses: "मासिक खर्च",
    savingsRate: "बचत दर",
    recentTransactions: "हाल के लेनदेन",
    quickActions: "त्वरित कार्य",
    financialVisualization: "वित्तीय विज़ुअलाइज़ेशन",
    thisMonth: "इस महीने",
    incomeMinusExpenses: "आय - खर्च",
    netBalance: "कुल बचत",
    netBalanceSubtitle: "आपकी बचत सही रास्ते पर है! 🚀",
    totalIncomeSubtitle: "इस महीने शानदार प्रगति! 📈",
    totalExpensesSubtitle: "खर्चों पर नज़र रखें! 🧐",
    yourAIFinanceCompanion: "आपका AI फाइनेंस साथी ✨",

    // New Dashboard Features
    calendarTracker: "कैलेंडर ट्रैकर",
    advancedAnalytics: "उन्नत विश्लेषण",
    budgetProgress: "बजट प्रगति",
    moneyMonster: "मनी मॉन्स्टर",
    aiSpendingCoach: "AI खर्च कोच",
    aiSpendingCoachSubtitle: "आपका व्यक्तिगत वित्तीय सलाहकार",
    warningTitle: "Tu {category} pe zyada udane laga hai bhai 😅",
    warningDesc: "₹{amount} spent this month",
    trendTitle: "Last 3 months spending pattern dekh",
    trendDescIncreasing: "Expenses are increasing trend mein hai",
    trendDescGood: "Good control maintain kar raha hai",
    suggestionTitle: "Smart suggestion for you",
    suggestionDesc: "Try to limit {category} expenses to ₹{limit} next month",
    proTipTitle: "💡 Pro Tip",
    proTipDesc: "बेहतर AI अंतर्दृष्टि के लिए नियमित रूप से खर्च लॉग करें। जितना अधिक डेटा, उतनी स्मार्ट सिफारिशें!",
    geoHeatmap: "भू हीटमैप",
    billScanner: "बिल स्कैनर",
    voiceEntry: "आवाज़ एंट्री",
    billReminders: "बिल रिमाइंडर",
    aiFinanceCoach: "AI वित्त कोच",
    smartBudgetPlanner: "धनसेतु बजट प्लानर",

    // DhanSetu Budget Planner
    budgetSubtitle: "सही बजट प्लानिंग ही बचत की शुरुआत है!",
    monthlyIncomeLabel: "मासिक आय (₹)",
    enterIncomePlaceholder: "जैसे, 50000",
    budgetCoachTip: "💡 **Coach Tip**: भाई, मैं आपके लिए 50-30-20 नियम के हिसाब से बजट बनाऊंगा। इससे आपकी बचत मस्त रहेगी!",
    totalBudget: "कुल बजट",
    totalSpent: "कुल खर्च",
    remaining: "बचत",
    overBudget: "बजट से ज्यादा!",
    budgetBreakdown: "बजट ब्रेकडाउन",
    smartRecommendations: "स्मार्ट सिफारिशें",
    budgetAlert: "चेतावनी",
    budgetUsageWarning: "आपने अपने {category} बजट का {percentage}% उपयोग कर लिया है। खर्च कम करने पर विचार करें।",
    budgetTipsTitle: "बजट टिप्स",
    budgetTip1: "• 50-30-20 नियम का पालन करें: 50% ज़रूरतें, 30% इच्छाएं, 20% बचत",
    budgetTip2: "• अपने बजट की मासिक समीक्षा करें",
    budgetTip3: "• बचत के लिए स्वचालित ट्रांसफर सेट करें",
    budgetTip4: "• बजट पर बने रहने के लिए रोज़ खर्च ट्रैक करें",

    viewAIInsights: "AI अंतर्दृष्टि देखें",
    advancedVisualizer: "उन्नत विज़ुअलाइज़र",

    // AI Insights
    aiInsightsTitle: "AI अंतर्दृष्टि",
    aiInsightsSubtitle: "बुद्धिमान वित्तीय विश्लेषण द्वारा संचालित",
    spendingAlert: "खर्च चेतावनी",
    spendingIncrease: "आपने {timePeriod} {category} पर ज्यादा खर्च किया",
    spendingIncreaseHi: "Aapne {timePeriod} {category} par zyada kharch kiya",
    thisMonthValue: "इस महीने: ₹{amount}",
    lastMonthValue: "पिछले महीने: ₹{amount}",
    nextMonthPrediction: "अगले महीने की भविष्यवाणी",
    predictedTotalExpenses: "अनुमानित कुल खर्च",
    confidence: "{score}% विश्वास",
    topSpendingCategories: "शीर्ष खर्च श्रेणियां",
    totalExpensesStat: "कुल खर्च का {percentage}%",
    smartSavingsTip: "स्मार्ट बचत टिप 💡",
    savingsTipLow: "भविष्य सुरक्षित रखने के लिए अपनी आय का 25% बचाने की कोशिश करें!",
    savingsTipHigh: "गज़ब! आपकी बचत दर औसत से ऊपर है।",
    monthlyGoal: "मासिक लक्ष्य 🎯",
    monthlyGoalDesc: "इस महीने ₹{amount} बचाने का लक्ष्य रखें।",
    spendingPatterns: "खर्च के पैटर्न",
    largestExpensePattern: "आपका सबसे बड़ा खर्चा {category} है (कुल का {percentage}%)।",
    savingsRatePattern: "फिलहाल आप अपनी आय का {percentage}% बचा रहे हैं।",
    expenseControlWarning: "⚠️ भाई, आमदनी से ज्यादा खर्चा हो रहा है! कंट्रोल करो।",
    expenseControlSuccess: "✅ सही जा रहे हो! आमदनी खर्च से ज्यादा है।",
    financialHealthScore: "वित्तीय स्वास्थ्य स्कोर",
    outOf100: "100 में से",
    healthScoreExcellent: "आप शानदार कर रहे हैं! दौलत बनाते रहें। 🚀",
    healthScoreGood: "आप सही रास्ते पर हैं, लेकिन सुधार की गुंजाइश है। 💪",
    healthySavings: "अच्छी बचत",
    lowSavings: "कम बचत",
    aiAnalyzed: "AI द्वारा विश्लेषण",

    // Categories
    food: "भोजन",
    travel: "यात्रा",
    entertainment: "मनोरंजन",
    rent: "किराया",
    income: "आय",
    grocery: "किराना",
    salary: "सैलरी",
    freelance: "फ्रीलांस",

    // Months
    january: "जनवरी",
    february: "फरवरी",
    march: "मार्च",
    april: "अप्रैल",
    may: "मई",
    june: "जून",
    july: "जुलाई",
    august: "अगस्त",
    september: "सितंबर",
    october: "अक्टूबर",
    november: "नवंबर",
    december: "दिसंबर",

    // Actions
    save: "सेव करें",
    cancel: "रद्द करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    back: "वापस",
    calculate: "गणना करें",

    // Splash Screen
    welcome: "आपका स्वागत है",
    smartBudgetAI: "DhanSetu AI",
    yourPersonalFinanceAssistant: "आपके पैसों का स्मार्ट साथी",
    getStarted: "शुरू करें",

    // Gamification
    points: "अंक",
    level: "स्तर",
    streak: "दिन स्ट्रीक",
    badges: "आपके बैज",
    challenges: "आज की चुनौतियां",
    leaderboard: "साप्ताहिक लीडरबोर्ड",
    yourRank: "आपकी रैंक",

    // AddExpense Component
    addTransaction: "लेनदेन जोड़ें",
    recordIncomeOrExpense: "अपनी आय या खर्च का रिकॉर्ड करें",
    transactionDetails: "लेनदेन विवरण",
    transactionType: "लेनदेन प्रकार",
    selectType: "प्रकार चुनें",
    expense: "खर्च",
    title: "शीर्षक",
    titlePlaceholder: "जैसे मैकडोनाल्ड, सैलरी, किराया",
    amount: "राशि",
    category: "श्रेणी",
    selectCategory: "श्रेणी चुनें",
    date: "दिनांक",
    pickDate: "दिनांक चुनें",
    saveTransaction: "लेनदेन सेव करें",
    preview: "पूर्वावलोकन",
    missingInformation: "जानकारी गायब",
    fillAllFields: "लेनदेन सेव करने के लिए कृपया सभी फ़ील्ड भरें।",
    invalidAmount: "गलत राशि",
    enterValidAmount: "कृपया एक वैध सकारात्मक राशि दर्ज करें।",
    transactionSaved: "लेनदेन सेव हो गया",
    transactionSavedDesc: "लेनदेन सफलतापूर्वक जोड़ दिया गया।",

    // Categories
    shopping: "खरीदारी",
    healthcare: "स्वास्थ्य सेवा",
    education: "शिक्षा",
    utilities: "उपयोगिता",
    other: "अन्य",

    // Common phrases
    languageChanged: "भाषा बदल गई!",
    congratulations: "बधाई हो!",
    newBadgeEarned: "नया बैज मिला!",
    keepSaving: "ऊपर चढ़ने के लिए बचत करते रहें!",
  }
};

export const getTranslation = (key: string, language: string = 'en'): string => {
  const langTranslations = translations[language as keyof typeof translations] || translations.en;
  return langTranslations[key as keyof typeof langTranslations] || key;
};

// Helper function to get category translation
export const getCategoryTranslation = (category: string, language: string = 'en'): string => {
  const categoryMap: Record<string, string> = {
    'Food': 'food',
    'Travel': 'travel',
    'Rent': 'rent',
    'Entertainment': 'entertainment',
    'Shopping': 'shopping',
    'Healthcare': 'healthcare',
    'Education': 'education',
    'Utilities': 'utilities',
    'Income': 'income',
    'Other': 'other',
    'Grocery': 'grocery',
    'Salary': 'salary',
    'Freelance': 'freelance',
    // Handle lowercase and existing category keys
    'food': 'food',
    'travel': 'travel',
    'rent': 'rent',
    'entertainment': 'entertainment',
    'shopping': 'shopping',
    'healthcare': 'healthcare',
    'education': 'education',
    'utilities': 'utilities',
    'income': 'income',
    'other': 'other',
    'grocery': 'grocery',
    'salary': 'salary',
    'freelance': 'freelance'
  };

  const translationKey = categoryMap[category] || 'other';
  return getTranslation(translationKey, language);
};
