// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhvgnxehtlkwkjwuykqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1odmdueGVodGxrd2tqd3V5a3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzY5NzksImV4cCI6MjA3Mzc1Mjk3OX0.xMGQ-xAzwDckWqdaxbzyYvcSIf68NdU-Rk6FdCyZ4ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});